export const sampleProducts = [
  {
    name: 'Striped Blue Business Shirt',
    description: 'Sharp striped business shirt in a classic blue palette. Made from breathable cotton blend with a tailored fit. Button-down collar, chest pocket, and a crisp finish ideal for the office or formal occasions.',
    price: 22900,
    compareAtPrice: null,
    currency: 'AMD',
    category: 'shirts',
    sizes: ['S', 'M', 'L', 'XL'],
    stock: [
      { size: 'S', quantity: 8 },
      { size: 'M', quantity: 8 },
      { size: 'L', quantity: 8 },
      { size: 'XL', quantity: 8 },
    ],
    images: ['https://images.unsplash.com/photo-1602810316498-ab67cf68c8e1?w=600&q=80'],
    isActive: true,
    featured: false,
    tags: ['shirt', 'business', 'striped', 'blue', 'formal'],
  },
  {
    name: 'Premium Cotton Polo – White',
    description: 'A refined white polo crafted from 100% premium piqué cotton. Features a ribbed collar, two-button placket, and a clean tailored cut. Effortlessly smart for both casual and semi-formal settings.',
    price: 17500,
    compareAtPrice: null,
    currency: 'AMD',
    category: 'shirts',
    sizes: ['S', 'M', 'L', 'XL'],
    stock: [
      { size: 'S', quantity: 10 },
      { size: 'M', quantity: 10 },
      { size: 'L', quantity: 10 },
      { size: 'XL', quantity: 10 },
    ],
    images: ['https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=600&q=80'],
    isActive: true,
    featured: false,
    tags: ['polo', 'white', 'cotton', 'casual', 'shirt'],
  },
  {
    name: 'Grey Slim Fit Trousers',
    description: 'Modern slim-fit trousers in a versatile heather grey. Tailored from a stretch-blend fabric for all-day comfort. Features a flat front, side pockets, and a clean hemline. Pairs well with blazers or polos.',
    price: 28500,
    compareAtPrice: null,
    currency: 'AMD',
    category: 'pants',
    sizes: ['30', '32', '34', '36'],
    stock: [
      { size: '30', quantity: 6 },
      { size: '32', quantity: 6 },
      { size: '34', quantity: 6 },
      { size: '36', quantity: 6 },
    ],
    images: ['https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600&q=80'],
    isActive: true,
    featured: false,
    tags: ['trousers', 'grey', 'slim-fit', 'pants', 'formal'],
  },
  {
    name: 'Formal Charcoal Pants',
    description: 'Elegant formal trousers in deep charcoal. Cut from a fine wool-blend fabric with a flat front and straight leg. Refined and versatile — a staple for business or evening occasions.',
    price: 31000,
    compareAtPrice: null,
    currency: 'AMD',
    category: 'pants',
    sizes: ['30', '32', '34'],
    stock: [
      { size: '30', quantity: 5 },
      { size: '32', quantity: 5 },
      { size: '34', quantity: 5 },
    ],
    images: ['https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600&q=80'],
    isActive: true,
    featured: false,
    tags: ['pants', 'charcoal', 'formal', 'wool-blend', 'trousers'],
  },
  {
    name: 'Brown Casual Blazer',
    description: 'Relaxed yet refined single-breasted blazer in warm brown. Crafted from a textured cotton-blend with unstructured shoulders for a casual, comfortable silhouette. Perfect for weekend outings or smart casual events.',
    price: 62000,
    compareAtPrice: null,
    currency: 'AMD',
    category: 'jackets',
    sizes: ['M', 'L', 'XL'],
    stock: [
      { size: 'M', quantity: 4 },
      { size: 'L', quantity: 4 },
      { size: 'XL', quantity: 4 },
    ],
    images: ['https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&q=80'],
    isActive: true,
    featured: false,
    tags: ['blazer', 'brown', 'casual', 'jacket', 'smart-casual'],
  },
  {
    name: 'Slim Fit Beige Suit',
    description: 'Sophisticated slim-fit suit in a warm beige tone. Tailored from a premium wool-blend with a notch lapel, two-button fastening, and a single rear vent. Includes matching trousers. Ideal for weddings and formal occasions.',
    price: 142000,
    compareAtPrice: null,
    currency: 'AMD',
    category: 'suits',
    sizes: ['48', '50', '52'],
    stock: [
      { size: '48', quantity: 2 },
      { size: '50', quantity: 2 },
      { size: '52', quantity: 2 },
    ],
    images: ['https://images.unsplash.com/photo-1594938298603-c8148c4b4e90?w=600&q=80'],
    isActive: true,
    featured: false,
    tags: ['suit', 'beige', 'slim-fit', 'formal', 'two-piece'],
  },
  {
    name: 'Double-Breasted Grey Suit',
    description: 'A statement double-breasted suit in classic charcoal grey. Constructed from Italian worsted wool with peak lapels, six-button front, and a structured silhouette. Includes matching trousers. The pinnacle of formal menswear.',
    price: 158000,
    compareAtPrice: null,
    currency: 'AMD',
    category: 'suits',
    sizes: ['48', '50', '52'],
    stock: [
      { size: '48', quantity: 2 },
      { size: '50', quantity: 2 },
      { size: '52', quantity: 2 },
    ],
    images: ['https://images.unsplash.com/photo-1490578474895-699cd4e2cf59?w=600&q=80'],
    isActive: true,
    featured: true,
    tags: ['suit', 'grey', 'double-breasted', 'formal', 'italian-wool'],
  },
  {
    name: 'Black Monk Strap Shoes',
    description: 'Sleek and distinguished black monk strap shoes crafted from full-grain leather. Features a double-buckle closure, leather sole, and a pointed toe. The ideal complement to formal suits and dress trousers.',
    price: 61000,
    compareAtPrice: null,
    currency: 'AMD',
    category: 'shoes',
    sizes: ['40', '41', '42', '43'],
    stock: [
      { size: '40', quantity: 5 },
      { size: '41', quantity: 5 },
      { size: '42', quantity: 5 },
      { size: '43', quantity: 5 },
    ],
    images: ['https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&q=80'],
    isActive: true,
    featured: false,
    tags: ['shoes', 'black', 'monk-strap', 'leather', 'formal'],
  },
  {
    name: 'Brown Leather Loafers',
    description: 'Classic brown leather loafers with a bit-buckle detail and a cushioned insole. Crafted from supple calfskin leather with a rubber sole for everyday comfort. Versatile enough for both business casual and weekend wear.',
    price: 54500,
    compareAtPrice: null,
    currency: 'AMD',
    category: 'shoes',
    sizes: ['40', '41', '42', '43'],
    stock: [
      { size: '40', quantity: 6 },
      { size: '41', quantity: 6 },
      { size: '42', quantity: 6 },
      { size: '43', quantity: 6 },
    ],
    images: ['https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=600&q=80'],
    isActive: true,
    featured: false,
    tags: ['shoes', 'brown', 'loafers', 'leather', 'casual'],
  },
  {
    name: 'Luxury Silk Tie – Navy',
    description: 'An exquisite navy silk tie woven from 100% pure silk. A slim 7cm blade with a clean, refined finish. Elevates any formal or business ensemble with understated elegance.',
    price: 10500,
    compareAtPrice: null,
    currency: 'AMD',
    category: 'accessories',
    sizes: ['ONE SIZE'],
    stock: [{ size: 'ONE SIZE', quantity: 18 }],
    images: ['https://images.unsplash.com/photo-1598808503746-f34c53b9323e?w=600&q=80'],
    isActive: true,
    featured: false,
    tags: ['tie', 'navy', 'silk', 'accessories', 'formal'],
  },
  {
    name: 'Leather Belt – Brown',
    description: 'Premium full-grain brown leather belt with a polished gold-tone pin buckle. 35mm width with a stitched edge that develops a natural patina over time. A timeless accessory for formal and casual looks alike.',
    price: 15000,
    compareAtPrice: null,
    currency: 'AMD',
    category: 'accessories',
    sizes: ['M', 'L', 'XL'],
    stock: [
      { size: 'M', quantity: 8 },
      { size: 'L', quantity: 8 },
      { size: 'XL', quantity: 8 },
    ],
    images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80'],
    isActive: true,
    featured: false,
    tags: ['belt', 'brown', 'leather', 'accessories', 'formal'],
  },
  {
    name: 'Formal Vest – Black',
    description: 'Tailored five-button formal vest in jet black. Cut from a fine twill fabric with a V-neckline, adjustable back strap, and a welt chest pocket. Pairs perfectly with a suit or dress shirt for a polished layered look.',
    price: 32000,
    compareAtPrice: null,
    currency: 'AMD',
    category: 'jackets',
    sizes: ['M', 'L', 'XL'],
    stock: [
      { size: 'M', quantity: 5 },
      { size: 'L', quantity: 5 },
      { size: 'XL', quantity: 5 },
    ],
    images: ['https://images.unsplash.com/photo-1555069519-127aadedf1ee?w=600&q=80'],
    isActive: true,
    featured: false,
    tags: ['vest', 'black', 'formal', 'jacket', 'waistcoat'],
  },
  {
    name: 'Luxury Wool Scarf – Grey',
    description: 'A soft and luxurious grey scarf crafted from fine merino wool. Generously sized with a classic fringe finish. Adds warmth and refinement to any winter outfit.',
    price: 12000,
    compareAtPrice: null,
    currency: 'AMD',
    category: 'accessories',
    sizes: ['ONE SIZE'],
    stock: [{ size: 'ONE SIZE', quantity: 14 }],
    images: ['https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=600&q=80'],
    isActive: true,
    featured: false,
    tags: ['scarf', 'grey', 'wool', 'accessories', 'winter'],
  },
  {
    name: 'Slim Fit Denim Jeans – Dark Blue',
    description: 'Sharp slim-fit jeans in a deep dark-blue wash. Made from stretch denim for a clean silhouette and all-day comfort. Five-pocket styling with a YKK zip and button waistband.',
    price: 26000,
    compareAtPrice: null,
    currency: 'AMD',
    category: 'pants',
    sizes: ['30', '32', '34', '36'],
    stock: [
      { size: '30', quantity: 7 },
      { size: '32', quantity: 7 },
      { size: '34', quantity: 7 },
      { size: '36', quantity: 7 },
    ],
    images: ['https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&q=80'],
    isActive: true,
    featured: false,
    tags: ['jeans', 'denim', 'dark-blue', 'slim-fit', 'pants'],
  },
  {
    name: 'Premium Black Turtleneck',
    description: 'A refined black turtleneck in soft merino-blend fabric. Features a ribbed fold-over collar, cuffs, and hem. Clean, minimal, and effortlessly sophisticated — perfect for layering under a blazer or wearing alone.',
    price: 21000,
    compareAtPrice: null,
    currency: 'AMD',
    category: 'shirts',
    sizes: ['S', 'M', 'L', 'XL'],
    stock: [
      { size: 'S', quantity: 6 },
      { size: 'M', quantity: 6 },
      { size: 'L', quantity: 6 },
      { size: 'XL', quantity: 6 },
    ],
    images: ['https://images.unsplash.com/photo-1516826957135-700dedea698c?w=600&q=80'],
    isActive: true,
    featured: false,
    tags: ['turtleneck', 'black', 'merino', 'shirt', 'knitwear'],
  },
];
